export interface HtxEarnsDto {
  data: {
    recommendProject: HtxEarnDto[];
  };
}

export interface HtxEarnDto {
  currency: string;
  projectList: HtxEarnProductDto[];
}

export interface HtxEarnProductDto {
  viewYearRate: number;
}

// const data = {
//   currency: 'TRX',
//   currencyBalance: '0.00',
//   icon: 'https://saving-doc.hbfile.net/prd/20210804/9b7ea9eebad24fdcb50c6595dfe95533.png',
//   minViewYearRate: 0.033069,
//   maxViewYearRate: 1.0,
//   tag: null,
//   tagName: null,
//   includeType: 2,
//   projectList: [
//     {
//       projectId: 91,
//       viewProjectId: '000H00031HTYMJ',
//       productId: 90,
//       term: 0,
//       calculationType: 0,
//       type: 0,
//       viewYearRate: 0.05,
//       maxViewYearRate: null,
//       projectStatus: 1,
//       projectStatusSort: 1,
//       miningSchedule: '5.90%',
//       finishAmount: 94452352.8209395,
//       totalAmount: 1600000000.0,
//       shelfType: 0,
//       viewStatus: 1,
//       projectLabelType: 0,
//       projectShowLabel: 2,
//       projectShowExtend: '{"originApy":0}',
//       currency: 'TRX',
//       icon: 'https://saving-doc.hbfile.net/prd/20210804/9b7ea9eebad24fdcb50c6595dfe95533.png',
//       projectEnumType: 5,
//       projectType: null,
//       financialProperty: 0,
//       startTime: 1628078400000,
//       endTime: 2543155200000,
//       peEarlyBuyFlag: null,
//       booking: null,
//       isPreOnline: 0,
//       startAmount: 16.0,
//       tag: null,
//       tagName: null,
//       tagApyValue: null,
//     },
//     {
//       projectId: null,
//       viewProjectId: '001H10931DOUQT',
//       productId: null,
//       term: 9999,
//       calculationType: 0,
//       type: 1,
//       viewYearRate: 0.034,
//       maxViewYearRate: 1.0,
//       projectStatus: 1,
//       projectStatusSort: 1,
//       miningSchedule: '0.70%',
//       finishAmount: 11120012.0,
//       totalAmount: 1600000000.0,
//       shelfType: 1,
//       viewStatus: 1,
//       projectLabelType: 0,
//       projectShowLabel: 0,
//       projectShowExtend: '{}',
//       currency: 'TRX',
//       icon: 'https://saving-doc.hbfile.net/prd/20210804/9b7ea9eebad24fdcb50c6595dfe95533.png',
//       projectEnumType: 2,
//       projectType: null,
//       financialProperty: 0,
//       startTime: 1700668800000,
//       endTime: 1861977600000,
//       peEarlyBuyFlag: null,
//       booking: null,
//       isPreOnline: 0,
//       startAmount: 1.0,
//       tag: null,
//       tagName: null,
//       tagApyValue: null,
//     },
//     {
//       projectId: null,
//       viewProjectId: null,
//       productId: null,
//       term: 9999,
//       calculationType: null,
//       type: 1,
//       viewYearRate: 0.033069,
//       maxViewYearRate: 0.67550915,
//       projectStatus: 1,
//       projectStatusSort: 1,
//       miningSchedule: null,
//       finishAmount: null,
//       totalAmount: null,
//       shelfType: null,
//       viewStatus: null,
//       projectLabelType: null,
//       projectShowLabel: null,
//       projectShowExtend: null,
//       currency: 'TRX',
//       icon: null,
//       projectEnumType: 6,
//       projectType: null,
//       financialProperty: null,
//       startTime: null,
//       endTime: null,
//       peEarlyBuyFlag: null,
//       booking: null,
//       isPreOnline: null,
//       startAmount: null,
//       tag: null,
//       tagName: null,
//       tagApyValue: null,
//     },
//     {
//       projectId: null,
//       viewProjectId: null,
//       productId: 17,
//       term: null,
//       calculationType: null,
//       type: 0,
//       viewYearRate: 0.0336,
//       maxViewYearRate: null,
//       projectStatus: 1,
//       projectStatusSort: 1,
//       miningSchedule: null,
//       finishAmount: null,
//       totalAmount: null,
//       shelfType: null,
//       viewStatus: null,
//       projectLabelType: null,
//       projectShowLabel: null,
//       projectShowExtend: null,
//       currency: 'TRX',
//       icon: null,
//       projectEnumType: 7,
//       projectType: null,
//       financialProperty: null,
//       startTime: null,
//       endTime: null,
//       peEarlyBuyFlag: null,
//       booking: null,
//       isPreOnline: null,
//       startAmount: null,
//       tag: null,
//       tagName: null,
//       tagApyValue: null,
//     },
//     {
//       projectId: null,
//       viewProjectId: null,
//       productId: null,
//       term: 9999,
//       calculationType: null,
//       type: null,
//       viewYearRate: null,
//       maxViewYearRate: null,
//       projectStatus: null,
//       projectStatusSort: 3,
//       miningSchedule: null,
//       finishAmount: null,
//       totalAmount: null,
//       shelfType: null,
//       viewStatus: null,
//       projectLabelType: null,
//       projectShowLabel: null,
//       projectShowExtend: null,
//       currency: 'TRX',
//       icon: null,
//       projectEnumType: 10,
//       projectType: null,
//       financialProperty: null,
//       startTime: null,
//       endTime: null,
//       peEarlyBuyFlag: null,
//       booking: null,
//       isPreOnline: null,
//       startAmount: null,
//       tag: null,
//       tagName: null,
//       tagApyValue: null,
//     },
//   ],
//   maxProject: null,
//   earnHomeShow: null,
// };
