export interface KucoinEarnsDto {
  data: KucoinEarnDto[];
}

export interface KucoinSecondEarnsDto {
  data: KucoinEarnDto[];
}

export interface KucoinEarnDto {
  currency: string;
  products: KucoinEarnProductDto[];
}

export interface KucoinEarnProductDto {
  // number
  apr: string;
  // number
  total_apr: string;
}

// const data = {
//   currency: 'USDT',
//   weight: 130,
//   user_available_balance: 0,
//   base_available_balance: 0,
//   max_coupon_apr: '0',
//   min_apr: '2.0000',
//   max_apr: '100.0000',
//   products: [
//     {
//       product_id: 2310,
//       group_id: 0,
//       group_name: '',
//       currency: 'USDT',
//       income_currency: 'USDT',
//       name: 'USDT-7D',
//       category: 'ACTIVITY',
//       category_order: 6,
//       type: 'MULTI_TIME',
//       tags: ['NEWBIE'],
//       apr: '100.0000',
//       pol_apr: '0',
//       total_apr: '100.0000',
//       min_apr: '100.0000',
//       max_apr: '100.0000',
//       duration: 7,
//       return_type: 'DEFAULT',
//       return_rates: [],
//       status: 'ONGOING',
//       status_order: 0,
//       coupon_available: false,
//       max_coupon_apr: '0',
//       user_coupons: [],
//       is_auto_lock: 0,
//       category_text: 'Ограниченные по времени мероприятия',
//       start_apply_countdown: 0,
//       end_apply_countdown: null,
//       lock_end_time: null,
//       apply_end_time: null,
//     },
//     {
//       product_id: 2152,
//       group_id: 0,
//       group_name: '',
//       currency: 'USDT',
//       income_currency: 'USDT',
//       name: 'USDT',
//       category: 'DEMAND',
//       category_order: 1,
//       type: 'SAVING',
//       tags: [],
//       apr: '5.0505',
//       pol_apr: '0',
//       total_apr: '5.0505',
//       min_apr: '5.0505',
//       max_apr: '5.0505',
//       duration: 0,
//       return_type: 'DEFAULT',
//       return_rates: [],
//       status: 'ONGOING',
//       status_order: 1,
//       coupon_available: false,
//       max_coupon_apr: '0',
//       user_coupons: [],
//       is_auto_lock: 1,
//       category_text: 'Гибкие сбережения',
//       start_apply_countdown: 0,
//       end_apply_countdown: null,
//       lock_end_time: null,
//       apply_end_time: null,
//     },
//     {
//       product_id: '103673',
//       group_id: 0,
//       group_name: 'BTC-U',
//       currency: 'USDT',
//       income_currency: 'USDT',
//       name: 'Bullish BTC',
//       category: 'SHARKFIN',
//       category_order: 2,
//       type: 'TIME',
//       tags: [],
//       apr: '11.0961',
//       pol_apr: '0',
//       total_apr: '11.0961',
//       min_apr: '4.0000',
//       max_apr: '11.0961',
//       duration: 7,
//       return_type: 'DEFAULT',
//       return_rates: [],
//       status: 'ONGOING',
//       status_order: 1,
//       coupon_available: false,
//       max_coupon_apr: '0',
//       user_coupons: [],
//       is_auto_lock: 0,
//       category_text: 'Shark Fin',
//       start_apply_countdown: 0,
//       end_apply_countdown: 649126,
//       lock_end_time: 1736928000000,
//       apply_end_time: 1736928000000,
//     },
//     {
//       product_id: 2451,
//       group_id: 0,
//       group_name: '',
//       currency: 'USDT',
//       income_currency: 'USDT',
//       name: 'USDT-35D',
//       category: 'ACTIVITY',
//       category_order: 6,
//       type: 'MULTI_TIME',
//       tags: [],
//       apr: '6.0000',
//       pol_apr: '0',
//       total_apr: '6.0000',
//       min_apr: '6.0000',
//       max_apr: '6.0000',
//       duration: 35,
//       return_type: 'DEFAULT',
//       return_rates: [],
//       status: 'ONGOING',
//       status_order: 1,
//       coupon_available: false,
//       max_coupon_apr: '0',
//       user_coupons: [],
//       is_auto_lock: 0,
//       category_text: 'Ограниченные по времени мероприятия',
//       start_apply_countdown: 0,
//       end_apply_countdown: null,
//       lock_end_time: null,
//       apply_end_time: null,
//     },
//     {
//       product_id: 2732,
//       group_id: 0,
//       group_name: '',
//       currency: 'USDT',
//       income_currency: 'USDT',
//       name: 'USDT-30D',
//       category: 'ACTIVITY',
//       category_order: 6,
//       type: 'MULTI_TIME',
//       tags: [],
//       apr: '5.5000',
//       pol_apr: '0',
//       total_apr: '5.5000',
//       min_apr: '5.5000',
//       max_apr: '5.5000',
//       duration: 30,
//       return_type: 'DEFAULT',
//       return_rates: [],
//       status: 'ONGOING',
//       status_order: 1,
//       coupon_available: false,
//       max_coupon_apr: '0',
//       user_coupons: [],
//       is_auto_lock: 0,
//       category_text: 'Ограниченные по времени мероприятия',
//       start_apply_countdown: 0,
//       end_apply_countdown: null,
//       lock_end_time: null,
//       apply_end_time: null,
//     },
//     {
//       product_id: 2506,
//       group_id: 0,
//       group_name: '',
//       currency: 'USDT',
//       income_currency: 'USDT',
//       name: 'USDT-14D',
//       category: 'ACTIVITY',
//       category_order: 6,
//       type: 'MULTI_TIME',
//       tags: [],
//       apr: '5.0000',
//       pol_apr: '0',
//       total_apr: '5.0000',
//       min_apr: '5.0000',
//       max_apr: '5.0000',
//       duration: 14,
//       return_type: 'DEFAULT',
//       return_rates: [],
//       status: 'ONGOING',
//       status_order: 1,
//       coupon_available: false,
//       max_coupon_apr: '0',
//       user_coupons: [],
//       is_auto_lock: 0,
//       category_text: 'Ограниченные по времени мероприятия',
//       start_apply_countdown: 0,
//       end_apply_countdown: null,
//       lock_end_time: null,
//       apply_end_time: null,
//     },
//     {
//       product_id: 2212,
//       group_id: 0,
//       group_name: '',
//       currency: 'USDT',
//       income_currency: 'USDT',
//       name: 'USDT',
//       category: 'ACTIVITY',
//       category_order: 6,
//       type: 'DEMAND',
//       tags: [],
//       apr: '2.0000',
//       pol_apr: '0',
//       total_apr: '2.0000',
//       min_apr: '2.0000',
//       max_apr: '2.0000',
//       duration: 0,
//       return_type: 'DEFAULT',
//       return_rates: [],
//       status: 'ONGOING',
//       status_order: 1,
//       coupon_available: false,
//       max_coupon_apr: '0',
//       user_coupons: [],
//       is_auto_lock: 0,
//       category_text: 'Ограниченные по времени мероприятия',
//       start_apply_countdown: 0,
//       end_apply_countdown: null,
//       lock_end_time: null,
//       apply_end_time: null,
//     },
//   ],
// };
